[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm ci',
  'cd backend && npm ci',
  'cd frontend && npm ci'
]

[phases.build]
cmds = [
  'cd backend && npm run build',
  'cd frontend && npm run build'
]

[start]
cmd = 'npm start'