[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x']
nixLibs = ['stdenv.cc.cc.lib']

[phases.install]
cmds = ['npm ci --only=production --ignore-scripts']

[phases.build]
cmds = [
  'npm ci',
  'npm run build'
]

[phases.start]
cmd = 'npm run start:prod'

[variables]
NODE_ENV = 'production'